theme: jekyll-theme-cayman
title: Notebook Drive's homepage
description: I have always loved writing. Whether it's copying down equations, my nighttime diary, or a to-do list that may or may not get completed, there's
something cathartic about pencil or pen to paper. That's the one sentence 'why' behind this.
